### ISSUE TITLE
c "namespace" in visual mode

### ISSUE THREAD

**Issue by bruno-** [richsoni/vim-ecliptic#1]
Nice plugin, I'll be using it because typing `"+` just isn't comfy sometimes.

I'm concerned about the `c` namespace in visual mode though. I **think** `c` is used with `visual` mode quite often and after installing this plugin there's now this "lag" (which totally makes sense).

I was thinking about the alternatives to `c` "namespace" to avoid this problem - so how about the feature that would enable setting a user defined key as a namespace? Leaving the default as-is is fine.

Personally, I think I would set it to `+` key so I'd have `+y` and `+yy` etc. `-` is a tempting option because it's even easier to type.

So, what do you say?

**Comment by kminh** [comment]
How about using `s` ? `s` doesn't seem to be used anyway, Vim Surround only uses `S` and `s` can also stand for "[s]ystem clipboard".
