### ISSUE TITLE
Ambiguity in <plug> mapping's name

### ISSUE THREAD

**Issue by kminh** [richsoni/vim-ecliptic#5]
Hello and thank you for this plugin.

Not sure if it's just me, but when I try visually selecting anything and press `cy` Vim doesn't copy the selected text right away (I need to press something else). This has something to do with the ambiguity of the <plug> mapping's name. When I make the following change it works as expected:

``` vim
vnoremap <silent> <Plug>EclipticVY_v    :call <SID>EclipticCopy(visualmode())<cr>
vnoremap <silent> <Plug>EclipticVY_V    :call <SID>EclipticCopy('V')<cr> # I think it makes sense to change this to _V too
```

This applies to visual deletion as well.

Btw, there's an `echo "here"` debug code that's lying around in your code.

**Comment by richsoni** [comment]
@kminh sorry for the really long delay.  I never got a notification for this.  

This works makes sense, and I looked at your code.  If you make a pull request, I would love to merge in your branch
